"""
First real PatchPlan for the UAAF Patch Engine.

This maintenance script applies a controlled, non-destructive patch to the UAAF
repository. It creates a readiness marker under 11_LOGS without modifying any
existing source file.

Run from the UAAF project root with:

    python 08_SCRIPTS/maintenance/patch_engine_first_real_patch.py
"""

from __future__ import annotations

import sys
from pathlib import Path


SCRIPT_FILE = Path(__file__).resolve()
SCRIPTS_ROOT = SCRIPT_FILE.parents[1]
PROJECT_ROOT = SCRIPT_FILE.parents[2]

if str(SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_ROOT))


from uaaf_tools.patch_engine import (  # noqa: E402
    PatchEngine,
    PatchOperation,
    PatchOperationType,
    PatchPlan,
    PatchStatus,
)


PATCH_ID = "uaaf-patch-engine-readiness-marker"
PATCH_VERSION = "1.0.0"

TARGET_FILE = PROJECT_ROOT / "11_LOGS" / "PATCH_ENGINE_READY.txt"

MARKER_CONTENT = """UAAF PATCH ENGINE READY
=======================

Patch ID      : uaaf-patch-engine-readiness-marker
Patch Version : 1.0.0
Status        : validated
Purpose       : confirm real PatchPlan execution inside the UAAF repository

Validated capabilities:
- PatchPlan validation
- Operation dispatch
- WriteFile execution
- Python package imports
- Structured PatchResult generation

This file was generated by the official UAAF Patch Engine.
"""


def build_patch_plan() -> PatchPlan:
    """Build the first real UAAF PatchPlan."""

    operation = PatchOperation(
        operation_id="create-patch-engine-readiness-marker",
        operation_type=PatchOperationType.WRITE_FILE,
        target_file=TARGET_FILE,
        parameters={
            "content": MARKER_CONTENT,
            "overwrite": False,
        },
        description=(
            "Create a non-destructive readiness marker proving that the "
            "Patch Engine can execute a real repository patch."
        ),
        required=True,
    )

    return PatchPlan(
        patch_id=PATCH_ID,
        name="Create Patch Engine readiness marker",
        version=PATCH_VERSION,
        description=(
            "First real UAAF PatchPlan. It creates a controlled marker file "
            "without modifying existing project source code."
        ),
        operations=[operation],
        create_backups=True,
        validate_python=True,
    )


def print_result(result: object) -> None:
    """Print a compact execution report."""

    print()
    print("=" * 72)
    print("UAAF Patch Engine - First Real PatchPlan")
    print("=" * 72)

    print(f"Patch ID : {result.patch_id}")
    print(f"Version  : {result.patch_version}")
    print(f"Status   : {result.status.value}")
    print(f"Message  : {result.message}")

    if result.error:
        print(f"Error    : {result.error}")

    print()
    print("Summary")
    print("-" * 72)
    print(f"Operations total      : {result.summary.total_operations}")
    print(f"Operations successful : {result.summary.successful_operations}")
    print(f"Operations failed     : {result.summary.failed_operations}")
    print(f"Files changed         : {result.summary.changed_files}")
    print(f"Backups created       : {result.summary.backup_files}")
    print(f"Files rolled back     : {result.summary.rolled_back_files}")
    print("=" * 72)


def main() -> int:
    """Execute the first real PatchPlan."""

    patch_plan = build_patch_plan()
    result = PatchEngine().execute(patch_plan)

    print_result(result)

    if result.status is not PatchStatus.SUCCESS:
        print()
        print("[FAIL] The first real PatchPlan did not complete successfully.")
        return 1

    if not TARGET_FILE.exists():
        print()
        print(
            "[FAIL] PatchResult reported success, but the readiness marker "
            "was not created."
        )
        return 1

    actual_content = TARGET_FILE.read_text(encoding="utf-8")

    if actual_content != MARKER_CONTENT:
        print()
        print(
            "[FAIL] The readiness marker content does not match the "
            "PatchPlan contract."
        )
        return 1

    print()
    print(f"[ OK ] Readiness marker created: {TARGET_FILE}")
    print("[ OK ] First real UAAF PatchPlan completed successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())